
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/matmul.ipynb

from torch import tensor
import torch

def matmul(a,b):
    return torch.einsum("ik,kj->ij",a,b) # mat mul with einsum